#############################################################
# Proxmox API variables
#############################################################
variable "proxmox_api_url" {
  description = "Proxmox api url"
  type        = string

  validation {
    condition     = can(regex("^http", var.proxmox_api_url))
    error_message = "Must be an URL, e.g. https://192.168.1.1:8006."
  }
}

variable "proxmox_api_username" {
  description = "Proxmox api username"
  type        = string
}

variable "proxmox_api_password" {
  description = "Proxmox api password"
  type        = string
}

variable "proxmox_api_otp" {
  description = "Proxmox api OTP"
  type        = string
  default     = ""
}

variable "proxmox_node_name" {
  description = "Name of the node where resources will be stored"
  type = string
}

variable "proxmox_api_tls_insecure" {
  description = "Allow insecure connection to Proxmox API"
  type        = bool
  default     = true
}
#############################################################
# Packer template variables
#############################################################
variable "template_description" {
  description = "Template description"
  default = "Generated by Packer"
  type = string
}

variable "vm_id" {
  description = "Virtual Machine ID number"
  type = number
}

variable "vm_name" {
  description = "Template name"
  default = "packer-template"
  type = string
}

variable "vm_storage_pool" {
  description = "Data store that supports `Disk image` and `Containers` (e.g. storage with type LVM-Thin)"
  type        = string
}

variable "vm_cores" {
  description = "Amount of CPU cores that will be allocated to a VM"
  type = number
  default = 2
}

variable "vm_memory" {
  description = "VM amount of memory"
  type = number
  default = 2048
}

variable "vm_sockets" {
  description = "VM amount of CPU sockets"
  type = number
  default = 1
}

variable "iso_file" {
  description = "Location of ISO file on the server. E.g. local:iso/<filename>.iso"
  type = string
}

variable "pool" {
  description = "Name of resource pool to create virtual machine in"
  type = string
  default = ""
}

#############################################################
# OS Settings
#############################################################
variable "username" {
  description = "Default username"
  type        = string
  default     = "deploy"
}

variable "user_password" {
  description = "Default password"
  type        = string
}

variable "time_zone" {
  description = "Time zone that will be used during OS setup"
  type        = string
  default     = "UTC"
}

#############################################################
# Module Actions
#############################################################
variable "remove_template" {
  description = "If set to true will invoke remove script and delete template from Proxmox node"
  type = bool
  default = false
}

variable "template" {
  description = "Folder name in the module that contains Packer source configuration"
  type = string
}